site_name: DNIT - Educação paro o trânsito
repo_name: "2024.1-DNIT-DOC"
repo_url: https://github.com/fga-eps-mds/2024.1-Dnit-DOC
docs_dir: docs

theme:
  name: material
  language: pt
  features:
           - navigation.tabs
  logo: assets/logos/dnitLogoBranco.png
  favicon: assets/logos/dnitLogoBrancoFundoAzul.png
nav:
  - Home: 
    - Início: index.md
  - Desenvolvimento Pré-Sprint: 
    - Semana 1: desenvolvimento/semana1.md
    - Semana 2: desenvolvimento/semana2.md
extra_css:
  - stylesheets/extra.css

 